imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

services:
    my.hwi.user:
        class: Local\HwioBundle\Security\Provider\HwiProvider
        arguments:
            userManager: "@fos_user.user_manager"
            properties:
              twitter_custom: twitterId
              facebook_custom: facebookId
    
    #in case i need to overide the default fos_user.registration.form.handler
    my.hwi.registration.form.handler:
        class: Local\HwioBundle\Form\Handler\RegistrationFormHandler
        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator"]
        scope: request
        public: false
        

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    translator:      ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# FOS User Bundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Local\HwioBundle\Entity\User

#HWI Oauth
hwi_oauth:
    connect:
        account_connector:  my.hwi.user
        registration_form:  fos_user.registration.form
        registration_form_handler:  fos_user.registration.form.handler
    firewall_name: main
    resource_owners:
        facebook_custom:
            type:                 oauth2
            client_id:            %facebook_id%
            client_secret:        %facebook_secret%
            access_token_url:     'https://graph.facebook.com/oauth/access_token'
            authorization_url:    'https://www.facebook.com/dialog/oauth'
            infos_url:            'https://graph.facebook.com/me'
            user_response_class:  'Local\HwioBundle\OAuth\Response\FacebookUserResponse'
            scope:                ''
            paths:
                identifier:       id
                nickname:         username
                realname:         name
                email:            email
                               
        twitter_custom:
            type:                 twitter
            client_id:            %twitter_id%
            client_secret:        %twitter_secret%
            request_token_url:    'https://api.twitter.com/oauth/request_token'
            access_token_url:     'https://api.twitter.com/oauth/access_token'
            authorization_url:    'https://api.twitter.com/oauth/authenticate'
            infos_url:            'http://api.twitter.com/1/account/verify_credentials.json'
            user_response_class:  'Local\HwioBundle\OAuth\Response\TwitterUserResponse'
            #realm:                ''
            paths:
                identifier:       id
                nickname:         screen_name
                realname:         name