parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     hwio
    database_user:     root
    database_password: 1q@w3e4r
    
    facebook_id:       280240708753866
    facebook_secret:   f3bfee46ecf34306e9853876fa69b9bd
    
    twitter_id:        7ZiwG3KMowHuocbGXFivLg
    twitter_secret:    egozdGqN2yZB7nxwP0QGX0eaYOWFbcSklfjAyyUuOcc

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            e73ab840398a24ffd7a0cb390f5f942af0379161
