jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    providers:
        chain_provider:
            chain:
              providers: [hwi_provider, fos_userbundle]
        hwi_provider:
            id: my.hwi.user
        fos_userbundle:
            id: fos_user.user_manager
  
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        main:
            oauth:
                resource_owners:
                    facebook_custom:    "/login-oauth/check-facebook"
                    twitter_custom:     "/login-oauth/check-twitter"
                login_path:      /login-oauth
                failure_path:    /login-oauth
                oauth_user_provider: 
                    service: my.hwi.user
                    #my.hwi.user
                    #hwi_oauth.user.provider.fosub_bridge
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        
        # NECESARY FOR LOGIN
        - { path: ^/profile, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
